package cisc3810.ngoum.registrarservices.api.model;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.util.Date;

@Entity
@Table(name = "students")
public class Student {
    @Id
    // Id generated by trigger from database
    @GeneratedValue(generator="increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    @Column(updatable = false, nullable = false)
    private Long id;

    //@OneToOne
    //private String username;

    // Email generated by trigger from database
    @Email
    private String email;

    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;

    @NotBlank
    private String gender;

    @NotNull
    private Date dateOfBirth;

    @ManyToOne
    @JoinColumn(name = "major_id", referencedColumnName = "id")
    private Major major;

    @PositiveOrZero
    @Max(4)
    private Double gpa;

    @Transient
    private short earnedCredits;

    @Transient
    private short attemptedCredits;

    protected Student() {}

    public Student(Long id, String email, String firstName, String lastName, String gender, Date dateOfBirth, Major major, Double gpa) {
        this.id = id;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.major = major;
        this.gpa = gpa;
    }

    public Student(String firstName, String lastName, String gender, Date dateOfBirth, Major major) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.major = major;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Major getMajor() {
        return major;
    }

    public void setMajor(Major major) {
        this.major = major;
    }

    public Double getGpa() {
        return gpa;
    }

    public void setGpa(Double gpa) {
        this.gpa = gpa;
    }

    public short getEarnedCredits() {
        return earnedCredits;
    }

    public void setEarnedCredits(short earnedCredits) {
        this.earnedCredits = earnedCredits;
    }

    public short getAttemptedCredits() {
        return attemptedCredits;
    }

    public void setAttemptedCredits(short attemptedCredits) {
        this.attemptedCredits = attemptedCredits;
    }

    @Override
    public String toString() {
        return String.format("Student : { id : %s, PersonalInfo: {email : \"%s\", firstName : \"%s\", lastName : \"%s\", gender : \"%s\", dateOfBirth : %s}, " +
                "AcademicInfo : {major : %s, gpa : %f, earnedCr : %d, attemptedCr : %d}}",
                this.id, this.email, this.firstName, this.lastName, this.gender, this.dateOfBirth, this.major.getName(), this.gpa, this.earnedCredits, this.attemptedCredits);    }
}
