package com.ngouma.brooklyn.cisc3810.registrarservices.api.model;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Entity
@Table(name = "instructors")
public class Instructor {
    @Id
    // Id generated by trigger from database
    @GeneratedValue(generator="increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    @Column(updatable = false, nullable = false)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "subject_id", referencedColumnName = "id")
    private Subject department;

    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;

    protected Instructor() {}

    public Instructor(Long id, Subject department, String firstName, String lastName) {
        this.id = id;
        this.department = department;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Subject getDepartment() {
        return department;
    }

    public void setDepartment(Subject department) {
        this.department = department;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
